# 파이썬 기초
## 데이터 사이언스 스쿨(https://datascienceschool.net) 을 기초로 합니다.
---------- 
### 배열의 생성과 변형

### Numpy의 자료형

![basic2_2_1](https://raw.githubusercontent.com/MAKU315/Master-project/master/Python/Numpy/img/2-1.PNG)

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [3]:
x = np.array([1.0, 2, 3])
x.dtype

dtype('float64')

![basic2_2_2](https://raw.githubusercontent.com/MAKU315/Master-project/master/Python/Numpy/img/2-2.PNG)

In [4]:
x = np.array([1,2,3],dtype='f')
x

array([1., 2., 3.], dtype=float32)

In [5]:
x[0] + x[1]

3.0

In [6]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [7]:
x

array(['1', '2', '3'], dtype='<U1')

#### 유니코드 문자열 합

In [8]:
x[0] + x[1]

'12'

### Inf & NaN

In [9]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0]) # 1/0 : inf | -1/0 : -inf | 0/0 : nan

C:\Users\korea\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\korea\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [10]:
np.log(0)

C:\Users\korea\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [11]:
np.exp(-np.inf)

0.0

### 배열 생성

![basic2_2_3](https://raw.githubusercontent.com/MAKU315/Master-project/master/Python/Numpy/img/2-3.PNG)

*  zeros_like : shape를 인풋으로 받음
*  ones_like : shape를 인풋으로 받음

In [12]:
a = np.zeros(5,dtype= 'i')
a

array([0, 0, 0, 0, 0], dtype=int32)

In [13]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
d = np.zeros(5, dtype="U4") # unicode 문자열
d

array(['', '', '', '', ''], dtype='<U4')

In [15]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [16]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [17]:
e = np.ones((2, 3, 4), dtype="i")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [18]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

![basic2_2_4](https://raw.githubusercontent.com/MAKU315/Master-project/master/Python/Numpy/img/2-4.PNG)

In [20]:
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있음
#### 특정한 규칙에 따라 증가하는 수열을 만든다.

In [21]:
np.arange(10)  # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
y = - np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계
print(y)
print(y.dtype)

[ -3  -5  -7  -9 -11 -13 -15 -17 -19]
int32


![basic2_2_5](https://raw.githubusercontent.com/MAKU315/Master-project/master/Python/Numpy/img/2-5.PNG)

In [23]:
np.linspace(0,100,5) # 시작, 끝(포함), 갯수  - 선형 5 구간으로 나누기

array([  0.,  25.,  50.,  75., 100.])

In [24]:
np.logspace(0.1, 1, 10) # 시작, 끝(포함), 갯수  - 로그를 10 구간으로 나누기

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

### Transpose(전치 연산)
    * 행과 열을 바꾸는 작업

In [25]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Reshape( 배열 크기 변형 )

In [27]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a.reshape(3,4) # 열로 움직임

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 튜플의 원소 중 하나는 -1이라는 숫자로 대체
#### 빈칸 채우기

In [30]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [32]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

### Flatten | ravel
    * 다차원 배열 -> 펼치기

In [33]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
b.flatten # flatten 함수형

<function ndarray.flatten>

In [35]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np.ravel

<function numpy.core.fromnumeric.ravel>

### flatten 과 ravel의 차이
    * flatten은 numpy의 배열에 관한 함수
    * ravel은 numpy 함수 -> 좀 더 자유로움

In [38]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [39]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [40]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [41]:
x

array([0, 1, 2, 3, 4])

### 한 차원 증가 시키기

In [42]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [43]:
x.reshape(5, -1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

![basic2_2_6](https://raw.githubusercontent.com/MAKU315/Master-project/master/Python/Numpy/img/2-6.PNG)

*  hstack : 열 더하기 - horizon
*  vstack : 행 더하기 - vertical
*  dstack : 깊이(depth) 방향으로 배열로 합치기
*  stack  : 사용자가 지정한 차원 연결 
    *  axis( 디폴트 0 ) : 0 - 맨 앞


In [44]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

### hstack

In [46]:
np.hstack([a1,a2]) # 열을 쌓기 - horizon

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [47]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### vstack

In [48]:
np.vstack([a1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### dstack
    *  안쪽의 원소의 차원 증가
    * (3 x 4 ) -> (3 x 4 x **2**)

In [49]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [52]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [53]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
c.shape

(2, 3, 4)

In [55]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [56]:
c.shape

(3, 2, 4)

### 인덱서와 stack의 차이
* stack 은 소괄호(parenthesis, () ) 를 사용
* 인덱서는 대괄호(bracket, [ ] ) 를 사용
    * r_ : 배열을 좌우로 연결 = hstack
    * c_ : 배열의 차원 증가 = vstack

In [57]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [58]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

#### tile : 동일한 배열 반복

In [59]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [60]:
np.tile(a, (2, 2)) # input은 정수 만

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

![basic2_2_7](https://raw.githubusercontent.com/MAKU315/Master-project/master/Python/Numpy/img/2-7.PNG)

In [61]:
np.tile(np.r_[np.tile(np.hstack([np.zeros(3),np.ones(2)]),(3,1)),np.arange(10,160,10).reshape(3,-1)],(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

## 2차원 그리드 포인트 생성

![basic2_2_8](https://raw.githubusercontent.com/MAKU315/Master-project/master/Python/Numpy/img/2-8.PNG)

* meshgrid : 사각형 영역을 구성하는 가로축의 점, 세로축의 점을 두 벡터의 인수로 받아 조합 출력
    * x 값과 y값의 행렬을 두개로 분리하여 출력

In [62]:
x = np.arange(3)
x

array([0, 1, 2])

In [63]:
y = np.arange(5)

In [64]:
X, Y = np.meshgrid(x,y)

In [65]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [66]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [67]:
[list(zip(x,y)) for x, y in zip(X,Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [68]:
import matplotlib.pylab as plt
plt.title("np.meshgrid로 만든 Grid Points")
plt.scatter(X, Y, linewidths=10)
plt.show()