# 파이썬 기초
## 데이터 사이언스 스쿨(https://datascienceschool.net) 을 기초로 합니다.

## Numpy 배열

    1. 모든 원소는 자료형
    2. 원소의 갯수 바 꿀 수 X
    3. 리스트 보다 빠르고 메모리 적음
 * Numpy 화용

In [1]:
import numpy as np

### 1차원 배열 만들기

In [2]:
ar = np.array([0,1,2,3,4,5])
print(ar)
type(ar)

[0 1 2 3 4 5]


numpy.ndarray

### 벡터화 연산
#### 벡터화 연산이 없으면 for 반복문으로 구현해야한다.

In [3]:
data = [0,1,2,3,4,5]

In [4]:
ans = []
for i in data:
    ans.append(2*i)
ans

[0, 2, 4, 6, 8, 10]

In [5]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5])

In [6]:
2 * x

array([ 0,  2,  4,  6,  8, 10])

### 리스트와의 차이
#### 리스트의 원소를 늘린다..!

In [7]:
y = [0,1,2,3,4,5]
2 * y

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

#### 벡터 곱 가능

In [8]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [9]:
a * b

array([10, 40, 90])

In [10]:
a == 2 

array([False,  True, False], dtype=bool)

In [11]:
(a == 2) & (b > 10)

array([False,  True, False], dtype=bool)

In [12]:
a = np.array([1, 2, 3,1])
b = np.array([10, 20, 30])

In [13]:
a * b # 길이가 다르면 error

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

## 2차원 배열

In [14]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
print(len(c)) # 행의 개수
print(len(c[0])) # 열의 개수

2
3


연습 문제 4.1.1

In [16]:
np.array([[10,20,30,40],[50,60,70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 3차원 배열

In [17]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [18]:
len(d), len(d[0]), len(d[0][0]) # 행 열 깊이

(2, 3, 4)

### 배열의 차원과 크기 확인

In [19]:
a = np.array([1, 2, 3])
print(a.ndim) # 차원의 크기
print(a.shape) # 배열의 상세 크기

1
(3,)


In [20]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape) # 행 x 열

2
(2, 3)


In [21]:
print(d.ndim)
print(d.shape) # 깊이 x 행 x 열

3
(2, 3, 4)


### 배열의 인덱싱
 * 일반적인 인덱싱과 같다

In [22]:
a = np.array([0,1,2,3,4])
a[2]

2

In [23]:
a[-1]

4

* 다차원 경우 shape처럼 추출
    * 차원은 축(axis)으로 생각

In [24]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

* tuple로 만들 수 있음 

In [25]:
x = a[0,2],a[0,-1]

In [26]:
type(x)

tuple

### 배열 슬라이싱
* : 활용

In [27]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
a[0, :] # 1 행 전체

array([0, 1, 2, 3])

In [29]:
a[1, :3] # 두번째 행의 세 번째 열 까지

array([4, 5, 6])

In [30]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

연습 문제 4.1.2

In [31]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

In [32]:
m[1,2]

7

In [33]:
m[2,-1]

14

In [34]:
m[1,1:3]

array([6, 7])

In [35]:
print([m[1,2],m[2,2]])
m[1:,2]

[7, 12]


array([ 7, 12])

In [36]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

### 배열 인덱싱
* 펜시 인덱싱(fancy indexing)/배열 인덱싱(array indexing)
* Query(질의) 기능을 수행
* 또 다른 ndarray을 활용한 인덱싱

사진 2

#### Boolean을 활용한 인덱싱
* 크기가 같아야한다

In [37]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [38]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [39]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [40]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

#### 정수 배열을 활용한 인덱싱
* 크기가 달라도 무관
    * 반복 추출도 가능

In [41]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8]) # 위치 정보
a[idx]

array([11, 33, 55, 77, 99])

In [42]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

#### 다차원도 가능

In [43]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [45]:
a[[2, 0, 1], :] # 위치 변환 가능

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

4.1.3

In [46]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [48]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [49]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])